name: furniture
version: 1.0.0
summary: Furniture App
description: A demo of Counter Application using Flutter
confinement: strict
base: core18
grade: stable
icon: snap/gui/icon.png
apps:
   furniture:
     command: furniture
     extensions: [flutter-master]
     plugs:
       - network
       - desktop
parts:
  counter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application